### ISSUE TITLE
[Dont Close] Checklist

### ISSUE THREAD

**Issue by idontreallywolf** [EmirMulic/Projekt2_Newton#28]
**V1 - Requirements**
- [ ] Save customers along with their accounts
- [ ] Register new customers with a unique person number
- [ ] Modify customer name
- [ ] Remove accounts individually
- [ ] Register accounts with unique IDs to specific users
- [ ] Display balance & interest when removing users &/ accounts
- [ ] Display information on selected user (accounts, transactions... )
- [ ] Deposit & Withdraw from accounts

**V2 - Requirements**
- [ ] Implement creditAccount
- [ ] Withdraw from creditAcc should only be possible if the amount doesn't exceed limit
- [ ] Only one free withdraw for creditAccounts
- [ ] When closing an account - correct balance & interest should be displayed.

**Comment by mitander** [comment]
Remove accounts individually - doesn't closeAccount(pNr, accountId) do this?

**Comment by idontreallywolf** [comment]
It is currently not possible to remove them 1 by 1 from the GUI. We need to be able to select a user then close only 1 of the accounts instead of having to close customer altogether

**Comment by mitander** [comment]
Yep, that's right. I thought closeAccount(accId) actually did close acoounts. But it's just a boolean check. smh
